create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.tasks enable row level security;

-- Demo policy: anyone with your public anon key can use this app.
-- Add Supabase Auth and per-user policies before deploying a multi-user app.
create policy "demo users can manage tasks"
on public.tasks
for all
to anon
using (true)
with check (true);
